/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Backend": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "Queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "db": {
      "token": string
      "type": "turso.index/database.Database"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}